name: SwashbuckleEnchants
version: ${project.version}
main: me.syfe.swashbuckleenchants.SwashbuckleEnchants
api-version: 1.13
authors: [Syfe]
description: Custom enchants that players can be given.
commands:
  itmgive:
    description: Apply Item Magnet enchant.
    usage: /<command>
