name: SwashbuckleEnchants
version: ${project.version}
main: me.syfe.swashbuckleenchants.SwashbuckleEnchants
api-version: 1.13
authors: [Syfe]
description: Swashbuckle Enchants plugin, this contains custom enchants that players can obtain.
commands:
  itmgive:
    description: Apply Item Magnet Enchant to item in hand.
    usage: /<command>
